name:                getline
version:             0.1.0.0
github:              "dspies-leapyear/getline"
license:             BSD3
author:              "David Spies"
maintainer:          "david@leapyear.io"
copyright:           "2019 David Spies"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dspies-leapyear/getline#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- ScopedTypeVariables

library:
  source-dirs: src

executables:
  getline-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - getline

tests:
  getline-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - getline
    - hspec
    - mtl
